[package]
name = "minimal"
version = "0.0.0"
edition = "2021"

[dependencies]
winfsp_wrs = { path = "../../winfsp_wrs" }
ctrlc = "3.4.2"

[build-dependencies]
winfsp_build = { path = "../../winfsp_build" }
