[package]
name = "memfs"
version = "0.0.0"
edition = "2021"

[dependencies]
winfsp_wrs = { path = "../../winfsp_wrs", features = [] }

[build-dependencies]
winfsp_build = { path = "../../winfsp_build" }
