[package]
name = "memfs"
version = "0.0.0"
edition = "2021"

[dependencies]
winfsp_wrs = { path = "../../winfsp_wrs" }
winfsp_wrs_build = { path = "../../winfsp_wrs_build" }

[build-dependencies]
winfsp_wrs_build = { path = "../../winfsp_wrs_build" }
